#!/bin/bash

# AWS Elastic Beanstalk 배포 스크립트
# 이 스크립트는 EB CLI가 설치되어 있다고 가정합니다.

echo "=== AWS Elastic Beanstalk 배포 가이드 ==="
echo ""
echo "1. EB CLI 설치 (이미 설치되어 있다면 건너뛰세요):"
echo "   brew install awsebcli"
echo ""
echo "2. AWS 자격 증명 설정:"
echo "   aws configure"
echo ""
echo "3. EB 애플리케이션 초기화:"
echo "   eb init -p ruby-3.0 saju-app --region ap-northeast-2"
echo ""
echo "4. EB 환경 생성 (처음 배포시):"
echo "   eb create saju-env --elb-type application"
echo ""
echo "5. 애플리케이션 배포:"
echo "   eb deploy"
echo ""
echo "6. Route53에서 saju.cvvcv.click 도메인 설정:"
echo "   - AWS 콘솔에서 Route53 접속"
echo "   - cvvcv.click 호스팅 영역 선택"
echo "   - 레코드 생성:"
echo "     * 레코드 이름: saju"
echo "     * 레코드 유형: CNAME"
echo "     * 값: EB 환경의 URL (예: saju-env.eba-xxxxxx.ap-northeast-2.elasticbeanstalk.com)"
echo ""
echo "7. SSL 인증서 설정:"
echo "   - AWS Certificate Manager에서 *.cvvcv.click 인증서 요청"
echo "   - EB 환경 구성에서 로드 밸런서에 인증서 적용"
echo "   - 다음 명령으로 설정:"
echo "     eb config"
echo ""
echo "8. 환경 변수 설정 (필요시):"
echo "   eb setenv KEY=value"
echo ""
echo "9. 애플리케이션 열기:"
echo "   eb open"
echo ""
echo "=== 수동 배포 단계 ==="